[package]
name = "blur"
version = "0.1.0"
authors = ["John Axel Eriksson <john@insane.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
imageproc = "0.19"
rusttype = "0.8"